name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install uv and project dependencies
        run: |
          pip install uv
          uv venv
          uv pip install --system .

      - name: Run lint
        run: make lint
        
      - name: Run Ruff Linter
        run: ruff check gendiff tests

      # 📌 Скачивание и подготовка CodeClimate Test Reporter
      - name: Download CodeClimate test reporter
        run: wget -O cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64

      - name: Set permissions for test reporter
        run: chmod +x cc-test-reporter

      - name: Prepare CodeClimate test reporter
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: ./cc-test-reporter before-build

      # 📌 Запуск тестов с покрытием кода
      - name: Run tests
        run: pytest --cov=gendiff --cov-report=xml

      # 📌 CodeClimate ожидает coverage.xml в текущей директории
      - name: Upload coverage report to CodeClimate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: ./cc-test-reporter after-build --exit-code $?
